server:
  port: 1127
spring:
  application:
    name: SpringBoot-School
  # MySQL
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: Rosmontis.7.6
    url: jdbc:mysql://1.117.59.169:3306/school_spring?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
  # Redis
  data:
    redis:
      host: 1.117.59.169
      port: 6379
      password: 654321sideR
      database: 0
      timeout: 1800000
      lettuce:
        pool:
          max-active: 20
          max-wait: -1
          max-idle: 5
          min-idle: 1
# Logging Config
#logging:
##  level:
##    gene.recombine.springboot: DEBUG
#  config: classpath:logback-spring.xml
# springdoc-openapi项目配置
knife4j:
  enable: false
springdoc:
  swagger-ui:
    #自定义swagger前端请求路径,输入http:localhost:8080/swagger-ui会自动重定向到swagger页面
    path: /swagger-ui
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs  #swagger后端请求地址
    enabled: true   #是否开启文档功能
  group-configs: #分组配置,可配置多个分组
    - group: 'default'             #分组名称
      paths-to-match: '/**'        #配置需要匹配的路径
      packages-to-scan: gene.recombine.stuhubsys    #配置要扫描包的路径,一般配置到启动类所在的包名